/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class kalkulator extends javax.swing.JFrame {
    
    String angka;
    int pilih;
    double angka1,angka2,jumlah;

    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
        angka="";
    }
    
    void angka1(){
        angka +="1";
        jTextField1.setText(angka);
    }
    
    void angka2(){
        angka +="2";
        jTextField1.setText(angka);
    }
           
    void angka3(){
        angka +="3";
        jTextField1.setText(angka);
    }    
    
    void angka4(){
        angka +="4";
        jTextField1.setText(angka);
    }    

    void angka5(){
        angka +="5";
        jTextField1.setText(angka);
    }

    void angka6(){
        angka +="6";
        jTextField1.setText(angka);
    }

    void angka7(){
        angka +="7";
        jTextField1.setText(angka);
    }

    void angka8(){
        angka +="8";
        jTextField1.setText(angka);
    }

    void angka9(){
        angka +="9";
        jTextField1.setText(angka);
    }

    void angka0(){
        angka +="0";
        jTextField1.setText(angka);
    }
    
    void koma(){
        angka +=".";
        jTextField1.setText(angka);
    }    
    
    void hasil(){
        switch(pilih){
            case 1:
                angka2=Double.parseDouble(angka);
                jumlah=angka1+angka2;
                angka=Double.toString(jumlah);
                jTextField1.setText(angka);
                break;
                
            case 2:
                angka2=Double.parseDouble(angka);
                jumlah=angka1-angka2;
                angka=Double.toString(jumlah);
                jTextField1.setText(angka);
                break;

            case 3:
                angka2=Double.parseDouble(angka);
                jumlah=angka1*angka2;
                angka=Double.toString(jumlah);
                jTextField1.setText(angka);
                break;

            case 4:
                angka2=Double.parseDouble(angka);
                jumlah=angka1/angka2;
                angka=Double.toString(jumlah);
                jTextField1.setText(angka);
                break;                
        }
    }
    
    void tambah(){
        angka1=Double.parseDouble(angka);
        jTextField1.setText("+");
        angka="";
        pilih=1;
    }
    
    void kurang(){
        angka1=Double.parseDouble(angka);
        jTextField1.setText("-");
        angka="";
        pilih=2;
    }
    
    void kali(){
        angka1=Double.parseDouble(angka);
        jTextField1.setText("*");
        angka="";
        pilih=3;
    }
    
    void bagi(){
        angka1=Double.parseDouble(angka);
        jTextField1.setText("/");
        angka="";
        pilih=4;
    }
    
    
    




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Bsatu = new javax.swing.JButton();
        Bdua = new javax.swing.JButton();
        Btiga = new javax.swing.JButton();
        Bempat = new javax.swing.JButton();
        Blima = new javax.swing.JButton();
        Benam = new javax.swing.JButton();
        Btujuh = new javax.swing.JButton();
        Bdelapan = new javax.swing.JButton();
        Bsembilan = new javax.swing.JButton();
        Bbagi = new javax.swing.JButton();
        Bkali = new javax.swing.JButton();
        Btambah = new javax.swing.JButton();
        Bkurang = new javax.swing.JButton();
        Bsamadengan = new javax.swing.JButton();
        Bnol = new javax.swing.JButton();
        Bhapus = new javax.swing.JButton();
        Bkoma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(40, 30));
        setMinimumSize(new java.awt.Dimension(40, 30));
        setResizable(false);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        Bsatu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Bsatu.setText("1");
        Bsatu.setMaximumSize(new java.awt.Dimension(40, 30));
        Bsatu.setMinimumSize(new java.awt.Dimension(40, 30));
        Bsatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsatuActionPerformed(evt);
            }
        });

        Bdua.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Bdua.setText("2");
        Bdua.setMaximumSize(new java.awt.Dimension(40, 30));
        Bdua.setMinimumSize(new java.awt.Dimension(40, 30));
        Bdua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BduaActionPerformed(evt);
            }
        });

        Btiga.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Btiga.setText("3");
        Btiga.setMaximumSize(new java.awt.Dimension(40, 30));
        Btiga.setMinimumSize(new java.awt.Dimension(40, 30));
        Btiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtigaActionPerformed(evt);
            }
        });

        Bempat.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Bempat.setText("4");
        Bempat.setMaximumSize(new java.awt.Dimension(40, 30));
        Bempat.setMinimumSize(new java.awt.Dimension(40, 30));
        Bempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BempatActionPerformed(evt);
            }
        });

        Blima.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Blima.setText("5");
        Blima.setMaximumSize(new java.awt.Dimension(40, 30));
        Blima.setMinimumSize(new java.awt.Dimension(40, 30));
        Blima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlimaActionPerformed(evt);
            }
        });

        Benam.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Benam.setText("6");
        Benam.setMaximumSize(new java.awt.Dimension(40, 30));
        Benam.setMinimumSize(new java.awt.Dimension(40, 30));
        Benam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenamActionPerformed(evt);
            }
        });

        Btujuh.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Btujuh.setText("7");
        Btujuh.setMaximumSize(new java.awt.Dimension(40, 30));
        Btujuh.setMinimumSize(new java.awt.Dimension(40, 30));
        Btujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtujuhActionPerformed(evt);
            }
        });

        Bdelapan.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Bdelapan.setText("8");
        Bdelapan.setMaximumSize(new java.awt.Dimension(40, 30));
        Bdelapan.setMinimumSize(new java.awt.Dimension(40, 30));
        Bdelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdelapanActionPerformed(evt);
            }
        });

        Bsembilan.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Bsembilan.setText("9");
        Bsembilan.setMaximumSize(new java.awt.Dimension(40, 30));
        Bsembilan.setMinimumSize(new java.awt.Dimension(40, 30));
        Bsembilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsembilanActionPerformed(evt);
            }
        });

        Bbagi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bbagi.setText("/");
        Bbagi.setMaximumSize(new java.awt.Dimension(40, 30));
        Bbagi.setMinimumSize(new java.awt.Dimension(40, 30));
        Bbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbagiActionPerformed(evt);
            }
        });

        Bkali.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bkali.setText("x");
        Bkali.setMaximumSize(new java.awt.Dimension(40, 30));
        Bkali.setMinimumSize(new java.awt.Dimension(40, 30));
        Bkali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkaliActionPerformed(evt);
            }
        });

        Btambah.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btambah.setText("+");
        Btambah.setMaximumSize(new java.awt.Dimension(40, 30));
        Btambah.setMinimumSize(new java.awt.Dimension(40, 30));
        Btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtambahActionPerformed(evt);
            }
        });

        Bkurang.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Bkurang.setText("-");
        Bkurang.setMaximumSize(new java.awt.Dimension(40, 30));
        Bkurang.setMinimumSize(new java.awt.Dimension(40, 30));
        Bkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkurangActionPerformed(evt);
            }
        });

        Bsamadengan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bsamadengan.setText("=");
        Bsamadengan.setMaximumSize(new java.awt.Dimension(40, 30));
        Bsamadengan.setMinimumSize(new java.awt.Dimension(40, 30));
        Bsamadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsamadenganActionPerformed(evt);
            }
        });

        Bnol.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        Bnol.setText("0");
        Bnol.setMaximumSize(new java.awt.Dimension(40, 30));
        Bnol.setMinimumSize(new java.awt.Dimension(40, 30));
        Bnol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnolActionPerformed(evt);
            }
        });

        Bhapus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bhapus.setText("C");
        Bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhapusActionPerformed(evt);
            }
        });

        Bkoma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bkoma.setText(".");
        Bkoma.setMaximumSize(new java.awt.Dimension(40, 30));
        Bkoma.setMinimumSize(new java.awt.Dimension(40, 30));
        Bkoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bsamadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bnol, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Bempat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bsatu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bdua, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Blima, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bdelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Btiga, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bkoma, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Benam, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bkali, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Bsembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(Bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bbagi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsembilan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bdelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bkali, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Benam, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Blima, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bempat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btiga, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btambah, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bdua, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsatu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bkoma, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnol, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsamadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(Bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtigaActionPerformed
        // TODO add your handling code here:
        angka3();
    }//GEN-LAST:event_BtigaActionPerformed

    private void BempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BempatActionPerformed
        // TODO add your handling code here:
        angka4();
    }//GEN-LAST:event_BempatActionPerformed

    private void BlimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlimaActionPerformed
        // TODO add your handling code here:
        angka5();
    }//GEN-LAST:event_BlimaActionPerformed

    private void BenamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenamActionPerformed
        // TODO add your handling code here:
        angka6();
    }//GEN-LAST:event_BenamActionPerformed

    private void BtujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtujuhActionPerformed
        // TODO add your handling code here:
        angka7();
    }//GEN-LAST:event_BtujuhActionPerformed

    private void BdelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdelapanActionPerformed
        // TODO add your handling code here:
        angka8();
    }//GEN-LAST:event_BdelapanActionPerformed

    private void BsembilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsembilanActionPerformed
        // TODO add your handling code here:
        angka9();
    }//GEN-LAST:event_BsembilanActionPerformed

    private void BnolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnolActionPerformed
        // TODO add your handling code here:
        angka0();
    }//GEN-LAST:event_BnolActionPerformed

    private void BsatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsatuActionPerformed
        // TODO add your handling code here:
        angka1();
    }//GEN-LAST:event_BsatuActionPerformed

    private void BduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BduaActionPerformed
        // TODO add your handling code here:
        angka2();
    }//GEN-LAST:event_BduaActionPerformed

    private void BtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtambahActionPerformed
        // TODO add your handling code here:
        tambah();
    }//GEN-LAST:event_BtambahActionPerformed

    private void BsamadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsamadenganActionPerformed
        // TODO add your handling code here:
        hasil();
    }//GEN-LAST:event_BsamadenganActionPerformed

    private void BkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkurangActionPerformed
        // TODO add your handling code here:
        kurang();
    }//GEN-LAST:event_BkurangActionPerformed

    private void BkaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkaliActionPerformed
        // TODO add your handling code here:
        kali();
    }//GEN-LAST:event_BkaliActionPerformed

    private void BbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbagiActionPerformed
        // TODO add your handling code here:
        bagi();
    }//GEN-LAST:event_BbagiActionPerformed

    private void BhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhapusActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        angka1=(int) 0.0;
        angka2=(int) 0.0;
        jumlah=(int) 0.0;
        angka="";
    }//GEN-LAST:event_BhapusActionPerformed

    private void BkomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkomaActionPerformed
        // TODO add your handling code here:
        koma();
    }//GEN-LAST:event_BkomaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bbagi;
    private javax.swing.JButton Bdelapan;
    private javax.swing.JButton Bdua;
    private javax.swing.JButton Bempat;
    private javax.swing.JButton Benam;
    private javax.swing.JButton Bhapus;
    private javax.swing.JButton Bkali;
    private javax.swing.JButton Bkoma;
    private javax.swing.JButton Bkurang;
    private javax.swing.JButton Blima;
    private javax.swing.JButton Bnol;
    private javax.swing.JButton Bsamadengan;
    private javax.swing.JButton Bsatu;
    private javax.swing.JButton Bsembilan;
    private javax.swing.JButton Btambah;
    private javax.swing.JButton Btiga;
    private javax.swing.JButton Btujuh;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
